-- 2025-08-08 23:50:58.077376
-- ## NEW VERSION:
CREATE TABLE IF NOT EXISTS categories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL
);

-- ## ROLL BACK:
DROP TABLE IF EXISTS categories;